Falcor 4.3 (#264)

diff --git a/Build/packman/packman b/Build/packman/packman
--- a/Build/packman/packman
+++ b/Build/packman/packman
@@ -1,9 +1,35 @@
 #!/bin/bash
 
-PM_PACKMAN_VERSION=5.14
+# Copyright 2019 NVIDIA CORPORATION
+
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+
+#     http://www.apache.org/licenses/LICENSE-2.0
+
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+set -e
+if echo $PM_VERBOSITY | grep -i "debug" > /dev/null ; then
+	set -x
+else
+	PM_CURL_SILENT="-s -S"
+	PM_WGET_QUIET="--quiet"
+fi
+PM_PACKMAN_VERSION=6.15
+
+# This is necessary for newer macOS
+if [ `uname` == 'Darwin' ]; then
+	export LC_ALL=en_US.UTF-8
+	export LANG=en_US.UTF-8
+fi
 
 # Specify where packman command exists
-export PM_INSTALL_PATH=$(dirname ${BASH_SOURCE})
+export PM_INSTALL_PATH="$(dirname "${BASH_SOURCE}")"
 
 add_packages_root_to_file()
 {
@@ -21,7 +47,7 @@ if [ -z "$PM_PACKAGES_ROOT" ]; then
 	# Set variable permanently using .profile for this user (if exists)
 	add_packages_root_to_file ~/.profile
 	add_packages_root_to_file ~/.bashrc
-	# Set variable temporarily in this process so that the following execution will work 
+	# Set variable temporarily in this process so that the following execution will work
 	export PM_PACKAGES_ROOT="${HOME}/packman-repo"
 fi
 
@@ -29,6 +55,63 @@ fi
 if [ ! -d "$PM_PACKAGES_ROOT" ]; then
 	echo "Creating packman packages repository at $PM_PACKAGES_ROOT"
 	mkdir -p "$PM_PACKAGES_ROOT"
+fi
+
+fetch_file_from_s3()
+{
+	SOURCE=$1
+	SOURCE_URL=http://bootstrap.packman.nvidia.com/$SOURCE
+	TARGET=$2
+	echo "Fetching $SOURCE from bootstrap.packman.nvidia.com ..."
+	if command -v wget >/dev/null 2>&1; then
+		wget $PM_WGET_QUIET -O$TARGET $SOURCE_URL
+	else
+		curl -o $TARGET $SOURCE_URL $PM_CURL_SILENT
+	fi
+}
+
+install_python()
+{
+	PLATFORM=`uname`
+	PROCESSOR=`uname -m`
+	PYTHON_VERSION=3.7.2
+
+	if [ $PLATFORM == 'Darwin' ]; then
+		PYTHON_PACKAGE=$PYTHON_VERSION-71-macos-x86_64
+	elif [ $PLATFORM == 'Linux' ] && [ $PROCESSOR == 'x86_64' ]; then
+		# This is temporary while we haven't built a static 3.7.2 that works on CentOS and Ubuntu
+		PYTHON_PACKAGE=3.6.8-linux-x86_64
+	elif [ $PLATFORM == 'Linux' ] && [ $PROCESSOR == 'aarch64' ]; then
+		PYTHON_PACKAGE=$PYTHON_VERSION-linux-aarch64-static
+	else
+		echo "Operating system not supported"
+		exit 1
+	fi
+
+	PYTHON_INSTALL_FOLDER="$PM_PACKAGES_ROOT/python/$PYTHON_PACKAGE"
+	if [ ! -d "$PYTHON_INSTALL_FOLDER" ]; then
+		mkdir -p "$PYTHON_INSTALL_FOLDER"
+	fi
+
+	export PM_PYTHON="$PYTHON_INSTALL_FOLDER/python"
+
+	if [ ! -f "$PM_PYTHON" ]; then
+		fetch_file_from_s3 "python@$PYTHON_PACKAGE.tar.gz" "/tmp/python@$PYTHON_PACKAGE.tar.gz"
+		if [ "$?" -eq "0" ]; then
+			echo "Unpacking python"
+			tar -xf "/tmp/python@$PYTHON_PACKAGE.tar.gz" -C "$PYTHON_INSTALL_FOLDER"
+		else
+			echo "Failed downloading the Python interpreter"
+			exit $?
+		fi
+	fi
+}
+
+# Ensure python is available:
+if [ -z "$PM_PYTHON_EXT" ]; then
+	install_python
+else
+	PM_PYTHON="$PM_PYTHON_EXT"
 fi
 
 # The packman module may be externally configured
@@ -39,28 +122,6 @@ else
 fi
 export PM_MODULE="$PM_MODULE_DIR/packman.py"
 
-fetch_file_from_s3() 
-{
-	SOURCE=$1
-	SOURCE_URL=http://packman-bootstrap.s3.amazonaws.com/$SOURCE
-	TARGET=$2
-	echo "Fetching $SOURCE from S3 ..."
-	if command -v wget >/dev/null 2>&1; then
-		wget --quiet -O$TARGET $SOURCE_URL
-	else
-		curl -o $TARGET $SOURCE_URL -s -S
-	fi		
-}
-
-# For now assume python is installed on the box and we just need to find it
-if command -v python2.7 >/dev/null 2>&1; then
-	export PM_PYTHON=python2.7
-elif command -v python2 >/dev/null 2>&1; then
-    export PM_PYTHON=python2
-else
-	export PM_PYTHON=python
-fi
-
 # Ensure the packman package exists:
 if [ ! -f "$PM_MODULE" ]; then
 	PM_MODULE_PACKAGE="packman-common@$PM_PACKMAN_VERSION.zip"
@@ -69,7 +130,7 @@ if [ ! -f "$PM_MODULE" ]; then
 	fetch_file_from_s3 $PM_MODULE_PACKAGE $TARGET
 	if [ "$?" -eq "0" ]; then
 		echo "Unpacking ..."
-		$PM_PYTHON -S -s -u -E "$PM_INSTALL_PATH/bootstrap/install_package.py" "$TARGET" "$PM_MODULE_DIR"
+		"$PM_PYTHON" -S -s -u -E "$PM_INSTALL_PATH/bootstrap/install_package.py" "$TARGET" "$PM_MODULE_DIR"
 		rm $TARGET
 	else
 		echo "Failure while fetching packman module from S3!"
@@ -83,7 +144,7 @@ export PM_7za_PATH="$PM_PACKAGES_ROOT/7za/$PM_7za_VERSION"
 if [ ! -d "$PM_7za_PATH" ]; then
     export PM_7za_PATH="$PM_PACKAGES_ROOT/chk/7za/$PM_7za_VERSION"
     if [ ! -d "$PM_7za_PATH" ]; then
-        $PM_PYTHON -S -s -u -E "$PM_MODULE" pull "$PM_MODULE_DIR/deps.packman.xml"
+        "$PM_PYTHON" -S -s -u -E "$PM_MODULE" pull "$PM_MODULE_DIR/deps.packman.xml"
         if [ "$?" -ne 0 ]; then
            echo "Failure while installing required 7za package"
            exit 1
@@ -94,7 +155,12 @@ fi
 # Generate temporary file name for environment variables:
 PM_VAR_PATH=`mktemp -u -t tmp.$$.pmvars.XXXXXX`
 
-$PM_PYTHON -S -s -u -E "$PM_MODULE" "$@" --var-path="$PM_VAR_PATH"
+if [ $# -ne 0 ]
+  then
+    PM_VAR_PATH_ARG=--var-path="$PM_VAR_PATH"
+fi
+
+"$PM_PYTHON" -S -s -u -E "$PM_MODULE" "$@" $PM_VAR_PATH_ARG
 exit_code=$?
 # Export the variables if the file was used and remove the file:
 if [ -f "$PM_VAR_PATH" ]; then
